site_name: Whirl
contact_email: thomas@arbousier.info
interests:
  - 1j/semaine, 1j de temps en temps
  - 3j/semaine
  - 5j/semaine
status:
  - indépendant(e)
  - tpe (max 4 personnes)
  - étudiant(e) / thésard
  - autre